**NumPy Array'i Oluşturmak**


In [125]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a=np.array([1,2,3,4])

In [5]:
type(a)

numpy.ndarray

In [7]:
np.array([3.12,5,6,7] , dtype="float32")

array([3.12, 5.  , 6.  , 7.  ], dtype=float32)

In [8]:
#sıfırdan array oluşturmak

In [9]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((3,5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [139]:
v= np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [140]:
[v[9], v[0]]

[27, 0]

In [141]:
[v[1], v[3]]

[3, 9]

In [14]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [15]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
np.random.normal(10,4,(3,4))

array([[14.28998207, 12.96013252, 15.49866839,  9.39796075],
       [ 9.35440954,  6.20299522,  7.88498113,  8.19156843],
       [11.13710317,  5.08001176,  6.39920214, 11.46284495]])

In [17]:
np.random.randint(0,10,(3,3))

array([[0, 1, 0],
       [0, 4, 3],
       [2, 8, 0]])

**NumPy Array Özelikleri**


* ndarray.ndim : Aksis (boyut) sayısını verir. Bu da “rank” olarak adlandırılır.
* ndarray.shape : Dizi boyutunu verir. a X b matrisi (a,b) olarak döner.
* ndarray.size : Dizideki eleman sayısını verir. Yani a*b işleminin sonucudur.
* ndarray.dtype : Dizideki eleman türünü döndürür.


In [18]:
import numpy as np

In [132]:
import numpy as np

np.array([3.14, 4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])

In [134]:
5*np.array([1, 2,3])

array([ 5, 10, 15])

In [131]:
import numpy as np

v = np.array([2, 1, 4, 3, 5])

np.sort(v)

array([1, 2, 3, 4, 5])

In [19]:
np.random.randint(10, size=10)

array([3, 5, 2, 6, 2, 7, 6, 7, 9, 9])

In [20]:
a=np.random.randint(10, size=10)

In [21]:
a.ndim

1

In [22]:
a.shape

(10,)

In [23]:
a.size

10

In [24]:
a.dtype

dtype('int32')

**Yeniden Şekillendirme(Reshaping)**

In [25]:
import numpy as np

In [26]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a=np.arange(1,10)

In [30]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a.ndim

1

In [32]:
b=a.reshape((1,9))

In [33]:
b.ndim

2

**Array Birleştirme**

In [34]:
import numpy as np

In [35]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [36]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [37]:
z=np.array([7,8,9])

In [38]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#iki boyutlu

In [40]:
a=np.array([[1,2,3]
            ,[4,5,6]])

In [41]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [44]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**Array Ayırma**

In [45]:
x=np.array([1,6,8,9,12,34,24,56])

In [46]:
np.split(x,[3,5])

[array([1, 6, 8]), array([ 9, 12]), array([34, 24, 56])]

In [48]:
a,b,c = np.split(x,[3,5])

In [49]:
a

array([1, 6, 8])

In [50]:
b

array([ 9, 12])

In [51]:
c

array([34, 24, 56])

In [52]:
#iki boyutlu ayırma

In [55]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [56]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [57]:
üst,alt= np.vsplit(m,[2])

In [58]:
üst

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [59]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

**Array Sıralama**

In [63]:
v=np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [64]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [66]:
v.sort()
v

array([1, 2, 3, 4, 5])

In [67]:
#iki boyutlu

In [71]:
m= np.random.normal(20,5, (3,3))
m

array([[15.07832421,  9.04667135, 19.46992503],
       [23.02548285, 21.83227891, 24.71804394],
       [28.01465465, 20.52580452, 22.69807962]])

In [73]:
np.sort(m, axis=1)

array([[ 9.04667135, 15.07832421, 19.46992503],
       [21.83227891, 23.02548285, 24.71804394],
       [20.52580452, 22.69807962, 28.01465465]])

**Index ile Elemanlara Erişmek**

In [75]:
a=np.random.randint(10,size=10)
a

array([2, 9, 4, 7, 1, 2, 2, 8, 9, 5])

In [76]:
a[0]

2

In [77]:
a[-1]

5

In [78]:
a[0] = 20
a

array([20,  9,  4,  7,  1,  2,  2,  8,  9,  5])

In [136]:
b=np.random.randint(10 ,size=(3,5))
b

array([[0, 6, 6, 3, 7],
       [2, 1, 0, 7, 4],
       [7, 4, 3, 8, 0]])

In [137]:
b[1,1]

1

In [80]:
b[0,0]

0

**Array Alt Kümesine Erişmek**

In [2]:
import numpy as np

In [3]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
a[0:3]

array([20, 21, 22])

In [5]:
a[:3]

array([20, 21, 22])

In [6]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [7]:
a[1::2]

array([21, 23, 25, 27, 29])

In [8]:
a[0::2]

array([20, 22, 24, 26, 28])

In [9]:
#iki boyutlu slice işlemleri

In [12]:
m=np.random.randint(10, size=(5,5))
m

array([[1, 2, 3, 9, 0],
       [2, 5, 7, 0, 3],
       [6, 4, 9, 6, 8],
       [2, 3, 5, 6, 5],
       [9, 0, 0, 4, 5]])

In [12]:
m=np.random.randint(10, size=(5,5))
m

array([[1, 2, 3, 9, 0],
       [2, 5, 7, 0, 3],
       [6, 4, 9, 6, 8],
       [2, 3, 5, 6, 5],
       [9, 0, 0, 4, 5]])

In [13]:
m[:,0]

array([1, 2, 6, 2, 9])

In [14]:
m[:,1]

array([2, 5, 4, 3, 0])

In [15]:
m[0,:]

array([1, 2, 3, 9, 0])

In [16]:
m[1,:]

array([2, 5, 7, 0, 3])

In [18]:
m[0:2 , 0:3]

array([[1, 2, 3],
       [2, 5, 7]])

In [19]:
m[: , 0:2]

array([[1, 2],
       [2, 5],
       [6, 4],
       [2, 3],
       [9, 0]])

In [20]:
m[1:3 , 0:2]

array([[2, 5],
       [6, 4]])

**Alt Küme Üzerinde İşlem Yapmak**

In [34]:
import numpy as np

In [35]:
a=np.random.randint(10, size=(5,5))
a

array([[0, 6, 7, 7, 5],
       [6, 1, 3, 2, 3],
       [5, 6, 1, 4, 4],
       [1, 0, 2, 9, 4],
       [3, 2, 9, 2, 0]])

In [36]:
alt_a = a[0:3,0:2]
alt_a

array([[0, 6],
       [6, 1],
       [5, 6]])

In [37]:
alt_a [0,0] = 9999
alt_a [1,1] = 888

In [38]:
alt_a

array([[9999,    6],
       [   6,  888],
       [   5,    6]])

In [39]:
a

array([[9999,    6,    7,    7,    5],
       [   6,  888,    3,    2,    3],
       [   5,    6,    1,    4,    4],
       [   1,    0,    2,    9,    4],
       [   3,    2,    9,    2,    0]])

In [40]:
m=np.random.randint(10, size=(5,5))
m

array([[7, 8, 5, 7, 9],
       [9, 5, 7, 4, 8],
       [0, 9, 4, 1, 1],
       [2, 2, 7, 7, 6],
       [4, 0, 2, 2, 0]])

In [41]:
alt_b=m[0:3,0:2].copy()
alt_b

array([[7, 8],
       [9, 5],
       [0, 9]])

In [42]:
alt_b[0,0] = 999
alt_b

array([[999,   8],
       [  9,   5],
       [  0,   9]])

In [43]:
m

array([[7, 8, 5, 7, 9],
       [9, 5, 7, 4, 8],
       [0, 9, 4, 1, 1],
       [2, 2, 7, 7, 6],
       [4, 0, 2, 2, 0]])

**Fancy Index ile Elemanlara Erişmek**

In [44]:
import numpy as np

In [46]:
a=np.arange(0,30,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [48]:
a[1]

3

In [49]:
a[3]

9

In [52]:
a[5]

15

In [53]:
[a[1], a[3],a[5]]

[3, 9, 15]

In [55]:
al_getir=[1,3,5]
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [56]:
a[al_getir]

array([ 3,  9, 15])

In [57]:
#iki boyutta fancy işlemleri

In [59]:
m=np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
satır=np.array([0,1])
sütun=np.array([1,2])
m[satır,sütun]

array([1, 5])

In [62]:
#basit index ile fancy index

In [63]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
m[0,[1,2]]

array([1, 2])

In [65]:
#slice ile fancy

In [66]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

**Koşullu Eleman İşlemleri**

In [67]:
import numpy as np

In [68]:
a=np.array([1,2,3,4,5])

In [69]:
a<3

array([ True,  True, False, False, False])

In [70]:
a[a<3]

array([1, 2])

In [71]:
a[a>3]

array([4, 5])

In [72]:
a[a>=3]

array([3, 4, 5])

In [73]:
a[a<=3]

array([1, 2, 3])

In [74]:
a[a!=3]

array([1, 2, 4, 5])

In [75]:
a[a==3]

array([3])

In [76]:
a*2

array([ 2,  4,  6,  8, 10])

In [77]:
a/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

**Matematiksel İşlemler**

 numpy_array.mean() : aritmetik ortalamayı bulur.

 numpy_array.median() : ortayı verir.

 numpy_array.var() : varyans bulur.

 numpy_array.std() : standart sapmasını bulur.

In [156]:
#axis = 1 : satırı alır
#axis = 0 : sütunları alır

In [143]:
import numpy as np

In [133]:
import numpy as np
5*np.array([1,2,3])

array([ 5, 10, 15])

In [80]:
a=np.array([1,2,3,4,5])

In [81]:
a-1

array([0, 1, 2, 3, 4])

In [82]:
#ufunc

In [84]:
np.subtract(a,1)

array([0, 1, 2, 3, 4])

In [85]:
np.add(a,1)

array([2, 3, 4, 5, 6])

In [86]:
np.multiply(a,4)

array([ 4,  8, 12, 16, 20])

In [87]:
np.divide(a,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [88]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [89]:
a**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [90]:
np.power(a,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [91]:
a % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [97]:
np.mod(a,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [94]:
np.absolute(np.array([-3]))

array([3])

In [95]:
np.sin(360)

0.9589157234143065

In [96]:
np.cos(180)

-0.5984600690578581

In [99]:
v=np.array([1,2,3])

In [100]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [101]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [102]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

**İstatistiksel Hesaplamalar**

In [103]:
v

array([1, 2, 3])

In [104]:
np.mean(v)

2.0

In [106]:
v.sum()

6

In [107]:
v.min()

1

In [108]:
v.max()

3

In [109]:
np.var(v)

0.6666666666666666

In [110]:
np.std(v)

0.816496580927726

**NumPy ile İki Bilinmeyenli Denklem Çözümü**

In [113]:
import numpy as np

In [121]:
#  5 * x0 + x1 =12
#  x0 +3 * x1 =10

In [122]:
a=np.array([[5,1] ,[1,3]])
b=np.array([12,10])
a

array([[5, 1],
       [1, 3]])

In [123]:
b

array([12, 10])

In [124]:
x=np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

**Transpoz Bulma**

In [152]:
#Matrislerin satırını sütun, sütunlarını satır yapmaya transpoz alma işlemi denir.Bir array’in transpozu  .T ile bulunur.

In [146]:
list_array = np.array([[1,2],
                       [4,5],
                       [7,8]])

In [149]:
print(list_array.T)

[[1 4 7]
 [2 5 8]]


**Matris Çarpımı**

In [150]:
a1 = np.array([[1,2],
               [2,0], 
               [3,1]])
a2 = np.array ([[4,3],
                [1,2]])

In [151]:
print(np.dot(a1,a2))

[[ 6  7]
 [ 8  6]
 [13 11]]


**Matris Birleştirme**

In [153]:
a3 = np.array([[1,2],
               [2,0],
               [3,1]])

In [154]:
print(np.concatenate([a3, a3], axis =0)) 
#Satıra göre birleştirmek istersek, satır = 0

[[1 2]
 [2 0]
 [3 1]
 [1 2]
 [2 0]
 [3 1]]


In [155]:
print(np.concatenate([a3, a3], axis =1)) 
#Sütuna göre  birleştirme yapmak istersek, sütun = 1

[[1 2 1 2]
 [2 0 2 0]
 [3 1 3 1]]
